<a href="https://colab.research.google.com/github/Mataf777/ClassColab/blob/main/Practica4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practica 4



In [ ]:
import numpy as np


# Matrices 3x3 con valores aleatorios entre 1 y 10
matriz1 = np.random.randint(1, 11, size=(3, 3))
matriz2 = np.random.randint(1, 11, size=(3, 3))

print("Matriz 1:")
print(matriz1)

print("\nMatriz 2:")
print(matriz2)

# Suma de matrices
suma = matriz1 + matriz2

# Resta de matrices
resta = matriz1 - matriz2

# Multiplicación de la primera matriz por 2
multiplicacion_escalar = matriz1 * 2

# Multiplicación matricial
multiplicacion_matricial = matriz1 @ matriz2

print("\nSuma de matrices:")
print(suma)

print("\nResta (matriz1 - matriz2):")
print(resta)

print("\nMatriz 1 multiplicada por 2:")
print(multiplicacion_escalar)

print("\nMultiplicación matricial (matriz1 @ matriz2):")
print(multiplicacion_matricial)


Matriz 1:
[[ 9  7  9]
 [ 9  6  9]
 [ 1 10  4]]

Matriz 2:
[[5 3 2]
 [1 8 5]
 [6 9 9]]

Suma de matrices:
[[14 10 11]
 [10 14 14]
 [ 7 19 13]]

Resta (matriz1 - matriz2):
[[ 4  4  7]
 [ 8 -2  4]
 [-5  1 -5]]

Matriz 1 multiplicada por 2:
[[18 14 18]
 [18 12 18]
 [ 2 20  8]]

Multiplicación matricial (matriz1 @ matriz2):
[[106 164 134]
 [105 156 129]
 [ 39 119  88]]
